services:
        ctf:
                restart: always
                build: ./
                read_only: true
                networks:
                        - internal
        proxy:
                restart: always
                image: nginx
                ports:
                        - '34652:34652'
                volumes:
                        - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
                networks:
                        - default
                        - internal
                depends_on:
                        - ctf

networks:
        default:
        internal:
                internal: true
